apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-platform-prod

namePrefix: prod-

resources:
- ../../base

patches:
- path: patch.yaml

images:
- name: ghcr.io/ragibcs/ml-inference-service
  newName: ghcr.io/ragibcs/ml-inference-service
  newTag: git-61c1b4140ccbada1be65af42c3a0c51823d9be69
