apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-platform

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: ml-inference-service
  app.kubernetes.io/part-of: ml-inference-platform
  app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/ragibcs/ml-inference-service
    newName: ghcr.io/ragibcs/ml-inference-service
    newTag: v1.0.0
