apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-platform-dev

namePrefix: dev-

resources:
  - ../../base

patches:
  - path: patch.yaml

images:
  - name: ghcr.io/ragibcs/ml-inference-service
    newName: ghcr.io/ragibcs/ml-inference-service
    newTag: dev-latest
